### ISSUE TITLE
`help from` leads to `AttributeError: 'EntriesTable' object has no attribute 'functions'`

### ISSUE THREAD

**Issue by tbm** [beancount/beanquery#115]
I typed `help from` and got a traceback:

```
beancount> help from
Traceback (most recent call last):
  File "/home/tbm/.local/bin/bean-query", line 8, in <module>
    sys.exit(main())
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 769, in main
    shell_obj.cmdloop()
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 193, in cmdloop
    super().cmdloop(intro)
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/lib/python3.9/cmd.py", line 308, in do_help
    func()
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 583, in help_from
    print(template.format(**generate_env_attribute_list(query_compile.TABLES['entries'])), file=self.outfile)
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 650, in generate_env_attribute_list
    functions = generate_env_attributes(wrapper, env.functions, aggregates=False)
AttributeError: 'EntriesTable' object has no attribute 'functions'
```

**Comment by blais** [comment]
This seems like a bug that's been introduced in refactoring. Poking around quickly it's not entirely clear what Daniele's intention was with functions in the new EntiresTable object. I'll let him handle it. @dnicolodi
