### ISSUE TITLE
Empty query (enter) leads to `AttributeError: 'NoneType' object has no attribute 'lower'`

### ISSUE THREAD

**Issue by tbm** [beancount/beanquery#116]
I'm not sure what I did to cause this.  I think I did "cursor up" to get a previous query, but not sure if that's related.

But basically now when I press "enter" in the prompt (without typing a query) I get:

```
beancount> 
Traceback (most recent call last):
  File "/home/tbm/.local/bin/bean-query", line 8, in <module>
    sys.exit(main())
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tbm/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 769, in main
    shell_obj.cmdloop()
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 193, in cmdloop
    super().cmdloop(intro)
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 202, in onecmd
    cmd, arg, line = self.parseline(line)
  File "/home/tbm/.local/lib/python3.9/site-packages/beanquery/shell.py", line 202, in parseline
    cmd = cmd.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by tbm** [comment]
Ok, I think this is unrelated to cursor up.  I think I pasted a query (which already had a newline at the end) and pressed enter, which resulted in the empty prompt (just enter).

**Comment by dnicolodi** [comment]
Yeah. The shell code is not in a great shape and there are almost no tests. I'm not surprised there are bugs. I have plans for a reorganization, but not much time to implement them. I'll try to prioritize it.
