### ISSUE TITLE
Cannot use `cost_date` as `date` in WHERE-clause

### ISSUE THREAD

**Issue by Philogy** [beancount/beanquery#121]
For postings in the base currency the `cost_date` is of type `None` leading to errors like the following if a query like `SELECT account, currency WHERE date_diff(today(), cost_date) >= 365 GROUP BY account, currency` is attempted:
```
Traceback (most recent call last):Traceback (most recent call last):
  File "/usr/lib/python3.10/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philippe/.local/lib/python3.10/site-packages/beancount/query/shell.py", line 271, in run_parser
    self.dispatch(statement)
  File "/home/philippe/.local/lib/python3.10/site-packages/beancount/query/shell.py", line 251, in dispatch
    return method(statement)
  File "/home/philippe/.local/lib/python3.10/site-packages/beancount/query/shell.py", line 416, in on_Select
    rtypes, rrows = query_execute.execute_query(c_query,
  File "/home/philippe/.local/lib/python3.10/site-packages/beancount/query/query_execute.py", line 317, in execute_query
    if c_where is None or c_where(context):
  File "/home/philippe/.local/lib/python3.10/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

Am I using `date_diff` / `cost_date` incorrectly? Is there a way to skip postings with a `cost_date` of type `NoneType`? Add a condition like `currency != 'EUR'` in the WHERE clause does filter out the entries but BQL doesn't seem to short-circuit conditions so it still returns that error

**Comment by Philogy** [comment]
Thanks @dnicolodi that fixed my issue, I was on the default `bean-query` installed alongside the main beancount package, after installing the above everything seems to work :smile:.
