### ISSUE TITLE
Unsupported operand type(s) for &: 'bool' and 'NoneType'

### ISSUE THREAD

**Issue by skfarhat** [beancount/beanquery#170]
**Version**: beancount 2.3.6

--- 

The following query: 

```
select * where account ~ "Expenses" and Findfirst('Assets:.*:Joint', other_accounts) 
```

fails with 

```
Traceback (most recent call last):
  File "/Users/sami/.pyenv/versions/3.11.4/lib/python3.11/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sami/.pyenv/versions/3.11.4/envs/sf-money/lib/python3.11/site-packages/beancount/query/shell.py", line 271, in run_parser
    self.dispatch(statement)
  File "/Users/sami/.pyenv/versions/3.11.4/envs/sf-money/lib/python3.11/site-packages/beancount/query/shell.py", line 251, in dispatch
    return method(statement)
           ^^^^^^^^^^^^^^^^^
  File "/Users/sami/.pyenv/versions/3.11.4/envs/sf-money/lib/python3.11/site-packages/fava/core/query_shell.py", line 110, in on_Select
    rtypes, rrows = execute_query(c_query, self.entries, self.options_map)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sami/.pyenv/versions/3.11.4/envs/sf-money/lib/python3.11/site-packages/fava/beans/funcs.py", line 44, in execute_query
    return query_execute.execute_query(  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sami/.pyenv/versions/3.11.4/envs/sf-money/lib/python3.11/site-packages/beancount/query/query_execute.py", line 276, in execute_query
    if c_where is None or c_where(context):
                          ^^^^^^^^^^^^^^^^
  File "/Users/sami/.pyenv/versions/3.11.4/envs/sf-money/lib/python3.11/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for &: 'bool' and 'NoneType'
```

`findfirst` seems to return None when it doesn't find an entry and None isn't compatible with & operator. 

Naive but: could we return `False` instead?

**Comment by dnicolodi** [comment]
This is a bug with `bean-query` as distributed with Beancount 2.3.6. This is already solved in the updated implementation in this repository.
