### ISSUE TITLE
SQL shell should check for data types for columns returning containers (and others)

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#49]
**[Original report](https://bitbucket.org/blais/beancount/issue/320) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I'm tracking my gross pay into my checking account from Income:Salary, and then transfering out from there into expense:income-tax, assets:401k, etc...

At the end of the year, I'd like to pull a report that shows me how much total I contributed to the Assets:401K account. However, I can't simply pull a `select sum(position) where account ~  "401K"` because I am also tracking purchases/sales in sub-accounts of Assets:401K. Rather, I'd like to do something like `select account,sum(position) where account ~ "401K" and other_accounts ~ "Checking"`, but this produces an error:

```
#!python

beancount> select account,sum(position) where account ~ "Checking" and other_accounts ~ "401K"
Traceback (most recent call last):
  File "/usr/lib64/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/shell.py", line 270, in run_parser
    self.dispatch(statement)
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/shell.py", line 250, in dispatch
    return method(statement)
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/shell.py", line 418, in on_Select
    self.options_map)
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_execute.py", line 316, in execute_query
    if c_where is None or c_where(context):
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 164, in match
    return bool(re.search(right, left, re.IGNORECASE))
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
beancount> select account,sum(position) where account ~ "401K" and other_accounts ~ "Checking"
Traceback (most recent call last):
  File "/usr/lib64/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/shell.py", line 270, in run_parser
    self.dispatch(statement)
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/shell.py", line 250, in dispatch
    return method(statement)
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/shell.py", line 418, in on_Select
    self.options_map)
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_execute.py", line 316, in execute_query
    if c_where is None or c_where(context):
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 164, in match
    return bool(re.search(right, left, re.IGNORECASE))
  File "/home/me/.config/pyVirtualEnvs/beancount_local/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

```

Is this expected behaviour? Am I doing something wrong? Is there another way to pull the report I want?

**Comment by dnicolodi** [comment]
Extensive type checking has been implemented and `bean-query` complains on this query:
```
bean-query /tmp/test.beans 'select sum(position) where account ~ "401K" and other_accounts ~ "Checking"'
ERROR: Operator match(set, str) not supported.
```
The error message is not the clearest but fixing that may require to extend the parser to store locations in the AST...
