### ISSUE TITLE
bean-query check for non-empty position fails

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#66]
**[Original report](https://bitbucket.org/blais/beancount/issue/13) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

beancount> select account, sum(cost(position)) where account ~'Assets:.*RRSP' and position != 0 group by 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blais/p/beancount/src/python/beancount/query/shell.py", line 223, in default
    self.dispatch(statement)
  File "/home/blais/p/beancount/src/python/beancount/query/shell.py", line 213, in dispatch
    return method(statement)
  File "/home/blais/p/beancount/src/python/beancount/query/shell.py", line 356, in on_Select
    self.options_map)
  File "/home/blais/p/beancount/src/python/beancount/query/query_execute.py", line 251, in execute_query
    if c_where is None or c_where(context):
  File "/home/blais/p/beancount/src/python/beancount/query/query_compile.py", line 111, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/home/blais/p/beancount/src/python/beancount/query/query_compile.py", line 93, in __call__
    return self.operator(self.operand(context))
  File "/home/blais/p/beancount/src/python/beancount/query/query_compile.py", line 111, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/home/blais/p/beancount/src/python/beancount/core/position.py", line 166, in __eq__
    return (self.number == other.number and
AttributeError: 'int' object has no attribute 'number'
beancount> select account, sum(cost(position)) where account ~'Assets:.*RRSP' and position group by 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blais/p/beancount/src/python/beancount/query/shell.py", line 223, in default
    self.dispatch(statement)
  File "/home/blais/p/beancount/src/python/beancount/query/shell.py", line 213, in dispatch
    return method(statement)
  File "/home/blais/p/beancount/src/python/beancount/query/shell.py", line 356, in on_Select
    self.options_map)
  File "/home/blais/p/beancount/src/python/beancount/query/query_execute.py", line 251, in execute_query
    if c_where is None or c_where(context):
  File "/home/blais/p/beancount/src/python/beancount/query/query_compile.py", line 111, in __call__
    return self.operator(self.left(context), self.right(context))
TypeError: unsupported operand type(s) for &: 'bool' and 'Position'
beancount>

**Comment by dnicolodi** [comment]
@blais you were a bit too pessimistic about the time frame in which this bug would have been fixed. It took four years but now beanquery rightfully complains that it cannot compare positions to integers:
```
bean-query test.beans "SEELCT account, sum(cost(position)) WHERE position != 0 GROUP BY  1"
ERROR: Operator equal(Position, int) not supported.
```
The error message could be improved, but that is another issue. It was not even particularly hard to fix. The foundation of beanquery is a nice design and it is fun to hack on it.

That said, I don't know what the query in the bug report was supposed to do because it seems unnecessary to filter out empty positions when computing their sum.
